### ISSUE TITLE
Update Tests to run Admin Service AdHoc

### ISSUE THREAD

**Issue by JDeBo** [opensourcecorp/workshops#11]
Having the admin service run on a timer during the tests makes it pretty tedious to troubleshoot the failure conditions. Disabling the timer during bats tests and running the service during the individual tests would give clearer delineation of when it's being called and identifying issues with the tests.

**Comment by ryapric** [comment]
I'm pretty sure it's [already disabled during the tests](https://github.com/opensourcecorp/workshops/blob/main/linux/scripts/test.bats#L29) -- does that not seem to be the case somehow?

**Comment by JDeBo** [comment]
Yep this is already a thing
