### ISSUE TITLE
Revisit & update slide deck for Linux workshop

### ISSUE THREAD

**Issue by ryapric** [opensourcecorp/workshops#5]
* TBD, I haven't looked at the previous one yet, but it's [here](https://github.com/opensourcecorp/workshops/blob/main/linux/docs/Linux-Workshop.odp).

**Comment by JDeBo** [comment]
Theme for CodeMash: Binary Vaporwave

Could be fun to try to incorporate

**Comment by ryapric** [comment]
Done on 2023-12-08
